<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $__env->yieldContent('title', 'Knowledge Base'); ?></title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #f5f5f5;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }

        header {
            background: #2c3e50;
            color: white;
            padding: 20px 0;
            margin-bottom: 30px;
        }

        header h1 {
            font-size: 2em;
            font-weight: 600;
        }

        nav {
            margin-top: 15px;
        }

        nav a {
            color: #ecf0f1;
            text-decoration: none;
            margin-right: 20px;
            padding: 8px 15px;
            border-radius: 4px;
            transition: background 0.3s;
        }

        nav a:hover {
            background: #34495e;
        }

        nav a.active {
            background: #3498db;
        }

        .search-box {
            margin: 20px 0;
            padding: 20px;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        .search-box input {
            width: 100%;
            padding: 12px;
            font-size: 16px;
            border: 2px solid #ddd;
            border-radius: 4px;
        }

        .search-box input:focus {
            outline: none;
            border-color: #3498db;
        }

        .content {
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        footer {
            margin-top: 40px;
            padding: 20px 0;
            text-align: center;
            color: #7f8c8d;
            font-size: 0.9em;
        }

        .badge {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 12px;
            font-size: 0.85em;
            font-weight: 500;
            margin-right: 5px;
        }

        .badge-primary {
            background: #3498db;
            color: white;
        }

        .badge-success {
            background: #2ecc71;
            color: white;
        }

        .badge-warning {
            background: #f39c12;
            color: white;
        }

        .badge-secondary {
            background: #95a5a6;
            color: white;
        }

        @media (max-width: 768px) {
            .container {
                padding: 10px;
            }

            header h1 {
                font-size: 1.5em;
            }

            nav a {
                display: block;
                margin: 5px 0;
            }
        }
    </style>
    <?php echo $__env->yieldContent('styles'); ?>
</head>
<body>
    <header>
        <div class="container">
            <h1>Knowledge Base</h1>
            <nav>
                <a href="index.html">Home</a>
                <a href="categories.html">Categories</a>
                <a href="tags.html">Tags</a>
            </nav>
        </div>
    </header>

    <div class="container">
        <?php echo $__env->yieldContent('content'); ?>
    </div>

    <footer>
        <div class="container">
            <p>Generated by Knowledge CLI - <?php echo e(date('Y-m-d H:i:s')); ?></p>
        </div>
    </footer>

    <?php echo $__env->yieldContent('scripts'); ?>
</body>
</html>
<?php /**PATH /Users/jordanpartridge/packages/conduit-ui/knowledge/resources/views/site/layout.blade.php ENDPATH**/ ?>